spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/keeperdb
    username: keeperuser
    password: password
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa.hibernate.ddl-auto: validate
